name: cctv setup
on:
  # 手动运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run hotel
        run: python ${{ github.workspace }}/hotel.py

        
