name: Cmys

on: [push]


permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run cctv
        run: python ${{ github.workspace }}/cctv.py

      - name: 提交总表更改
        run: |
          git config --local user.name "xzw832" 
          git config --local user.email "g832@x-zw.com"
          git add .
          git commit cctv.txt -m "Add generated file"
          git push -f
