name: Cmys

on:
  schedule:
    - cron: '0 11,23 * * *'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet
        
      - name: 先提交信息
        run: |
          git config --local user.name "xzw832" 
          git config --local user.email "g832@x-zw.com"
      - name: Run itv
        run: python ${{ github.workspace }}/itv.py
      - name: Sleep for 30 seconds
        run: sleep 10s
      - name: 提交总表更改
        run: |
          git add .
          git commit itv.txt -m "Add generated file"
          git push -f
