name: Get Live Source Resolution

on:
  # 手动运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 安装FFmpeg
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # 设置FFmpeg路径到PATH环境变量
      - name: Add FFmpeg to PATH
        run: |
          echo "export PATH=$PATH:/usr/bin/ffmpeg" >> $GITHUB_ENV

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # 安装ffmpeg-python库
      - name: Install ffmpeg-python
        run: |
          pip install ffmpeg-python

      # 运行你的Python脚本
      - name: Run your Python script
        run: |
          python /home/runner/work/cmys/cmys/url_ffmpeg.py
